# .readthedocs.yaml

version: 2

# Define the Python requirements for building the documentation
python:
  install:
    - requirements: doc/requirements.txt

# Define the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Sphinx configuration file
sphinx:
  configuration: sphinx/conf.py
